
[build]
  command = "npm run build"
  publish = ".netlify/functions"

# Atau jika output ke build/
[build]
  command = "npm run build"  
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200