# fitness application
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server-ticketing
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    networks:
      - ticketing_net

  db:
    image: mysql:latest
    container_name: mysql-ticketing
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-ticketing-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "${DB_HOST}",
          "-u",
          "${DB_USERNAME}",
          "--password=${DB_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - ticketing_net

  redis:
    image: redis:7-alpine
    container_name: redis-ticketing
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - ticketing_net

volumes:
  mysql-ticketing-data:

networks:
  ticketing_net:
