# fitness application
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ticketing_app
    restart: unless-stopped
    env_file:
      - .env

    ports: # delete for production  | use only for development
      - "5004:5004"
    expose:
      - "5004"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q --spider http://localhost:5002/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes: # delete on production | use only for development
      - .:/app
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ecommerce.rule=Host(`tiketku.ahmadfiqrioemry.com`)"
    #   - "traefik.http.services.ecommerce.loadbalancer.server.port=5004"
    #   - "traefik.http.routers.ecommerce.entrypoints=websecure"
    #   - "traefik.http.routers.ecommerce.tls.certresolver=letsencrypt"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
